### ISSUE TITLE
Script doesn't work due to headers error.

### ISSUE THREAD

**Issue by tavdog** [willowgreengroup/TextEditor#1]
Login cookie never gets set due to the error : PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/blah/edit.php:21)

**Comment by quelixir** [comment]
Thanks for submitting this issue. Can you see if the commits I've made to master solve the problem?

**Comment by tavdog** [comment]
New code gives error : PHP Parse error:  syntax error, unexpected '}', expecting end of file in /home/blah/TextEditor/TextEditor.php on line 89
Fixed by delete } at line 89.
